<?php

namespace controleaccespresence\AdminBundle\Repository;

/**
 * EventsFlameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsFlameRepository extends \Doctrine\ORM\EntityRepository
{
}
