<?php

namespace controleaccespresence\AdminBundle\Repository;

/**
 * ListenoireBadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListenoireBadgeRepository extends \Doctrine\ORM\EntityRepository
{
}
