<?php

namespace controleaccespresence\AdminBundle\Repository;

/**
 * LogAccesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogAccesRepoitory extends \Doctrine\ORM\EntityRepository
{
}
