<?php

namespace controleaccespresence\AdminBundle\Repository;

/**
 * LogHTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogHTRepository extends \Doctrine\ORM\EntityRepository
{
}
