<?php
namespace controleaccespresence\AdminBundle\Repository;

/**
 * SalleServeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleServeurRepository extends \Doctrine\ORM\EntityRepository
{
}
